apiVersion: v1
kind: Service
metadata:
  labels:
    app: eshop
    component: frontend
  name: frontend
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: eshop
    component: frontend
  type: LoadBalancer