apiVersion: v1
kind: Service
metadata:
  labels:
    app: starwars
    component: starwarsfe
  name: starwarsfe
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: starwars
    component: starwarsfe
  type: LoadBalancer
