apiVersion: v1
kind: Service
metadata:
  labels:
    app: starwars
    component: starwars-fe
  name: starwars-fe
spec:
  ports:
  - port: 81
    targetPort: 8080
  selector:
    app: starwars
    component: starwars-fe
  type: LoadBalancer
